resource_types:
- name: telegram-notification
  type: docker-image
  source:
    repository: w32blaster/concourse-telegram-notifier
    tag: latest

resources:
- name: telegram
  type: telegram-notification
  source:
    bot_token: ((bot_token))

- name: terraform-repo
  type: git
  icon: github
  source:
    uri: https://github.com/Yura11/server_depoy.git
    branch: main

jobs:
- name: tf-destroy
  plan:
    - get: terraform-repo
      trigger: true
    - task: run-terraform-destroy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: hashicorp/terraform
            tag: latest
        inputs:
          - name: terraform-repo
        params:
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_key))
        run:
          path: sh
          args:
            - -exc
            - |
              cd terraform-repo
              terraform init
              terraform plan
              terraform destroy --auto-approve
      on_success:
        put: telegram
        params:
          chat_id: ((chat_id))
          text: |
            :tf-destroy: *Job Succeeded*:
          pull_repository: true
      on_failure:
        put: telegram
        params:
          chat_id: ((chat_id))
          text: |
            :tf-destroy: *Job Failed*:
          pull_repository: true
