---
- name: Install Docker on Ubuntu Server
  hosts: ec2_instances
  become: true
  gather_facts: yes
  ignore_errors: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - docker.io
          - python3-pip
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
        executable: pip3

    - name: Clone Git repository
      git:
        repo: https://github.com/Yura11/docker_deploy.git
        dest: /home/docker_deploy

    - name: Build Docker image
      docker_image:
        source: "build"
        build:
          path: /home/docker_deploy
        name: server_build
        tag: 1.0

    - name: Run Docker container
      docker_container:
        name: server_build_
        image: server_build:1.0
        state: started
        ports:
          - "7777:7777"
        detach: true

    - name: Execute custom Bash script
      shell: |
        #!/bin/bash
    
        docker run -d --restart always --privileged -P --name st-agent --memory 512MB \
          -v /:/hostfs:ro \
          -v /sys/:/hostfs/sys:ro \
          -v /var/run/:/var/run/ \
          -v /sys/kernel/debug:/sys/kernel/debug \
          -v /etc/passwd:/etc/passwd:ro \
          -v /etc/group:/etc/group:ro \
          -v /dev:/hostfs/dev:ro \
          -v /var/run/docker.sock:/var/run/docker.sock:ro \
          -e INFRA_TOKEN=8f140222-89a0-4ce6-a747-690eb41e0c45 \
          -e REGION=EU \
          sematext/agent:latest
      args:
        executable: /bin/bash
