---
- name: use serverdp playbook
  hosts: ec2_instances
  become: true
  gather_facts: yes
  ignore_errors: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: serverdp
      system_manager: y.belichenko007@gmail.com
