global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'my_app'
    static_configs:
      - targets: ['localhost:7777']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']



  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: .+
        action: keep
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: .+
        action: labelmap


 
