---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install ca-certificates and curl
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create directory for apt keyrings
  command: mkdir -m 0755 -p /etc/apt/keyrings

- name: Download Docker GPG key
  command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

- name: Add Docker repository to Apt sources
  command: >
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt cache after adding Docker repository
  apt:
    update_cache: yes

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Clone Git repository
  git:
    repo: https://github.com/Yura11/docker_deploy.git
    dest: /home/docker_deploy

- name: Clone Git repository
  git:
    repo: https://github.com/Yura11/server_depoy.git
    dest: /home/server_depoy

- name: Build Docker image
  docker_image:
    name: server_build:1.0
    build:
      path: /home/docker_deploy

- name: Run Docker container
  docker_container:
    name: server_build_container
    image: server_build:1.0
    state: started
    ports:
      - "7777:7777"
    detach: true

- name: Run Docker Compose from defaults
  command: sudo docker-compose up -d
  args:
    chdir: /home/server_depoy
  become: yes
