---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker dependencies
  apt:
    name:
      - docker.io
      - python3-pip
    state: present

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present
    executable: pip3

- name: Clone Git repository
  git:
    repo: https://github.com/Yura11/docker_deploy.git
    dest: /home/docker_deploy

- name: Clone Git repository
  git:
    repo: https://github.com/Yura11/server_depoy.git
    dest: /home/server_depoy

- name: Build Docker image
  docker_image:
    name: server_build:1.0
    build:
      path: /home/docker_deploy

- name: Run Docker container
  docker_container:
    name: server_build_container
    image: server_build:1.0
    state: started
    ports:
      - "7777:7777"
    detach: true

- name: Download Prometheus Docker image
  docker_image:
    name: prom/prometheus
    tag: latest


- name: Copy Prometheus configuration file into the container
  command: docker cp /home/server_depoy/prometheus.yml prometheus_container:/etc/prometheus/prometheus.yml
  
- name: Run Prometheus container
  docker_container:
    name: prometheus_container
    image: prom/prometheus
    state: started
    ports:
      - "9090:9090"
    volumes:
      - /home/docker_deploy/prometheus:/etc/prometheus
    detach: true

- name: Download Grafana Docker image
  docker_image:
    name: grafana/grafana
    tag: latest

- name: Run Grafana container
  docker_container:
    name: grafana_container
    image: grafana/grafana
    state: started
    ports:
      - "3000:3000"
    detach: true

- name: Download Node Exporter Docker image
  docker_image:
    name: prom/node-exporter
    tag: latest

- name: Run Node Exporter container
  docker_container:
    name: node_exporter_container
    image: prom/node-exporter
    state: started
    ports:
      - "9100:9100"
    detach: true

- name: Trigger container stop
  notify: Stop containers

- name: Trigger container start
  notify: Start containers
